name: Lint
on: [push]
jobs:
  Check-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.x
          architecture: x64
      - name: Install Requirements
        run: make install-dev
      - name: Lint Code
        run: make flake8
